services:
  mcp:
    build:
      context: ./sample-deep-research-mcp
    env_file: .env
    environment:
      BIND_HOST: 0.0.0.0
      BIND_PORT: 8000
      TRANSPORT: sse
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mcp.rule=Host(`mcp.localhost`)
      - traefik.http.routers.mcp.entrypoints=websecure
      - traefik.http.routers.mcp.tls=true
      - traefik.http.services.mcp.loadbalancer.server.port=8000
