version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.dev.acme.tlschallenge=true
      - --certificatesresolvers.dev.acme.email=you@example.com
      - --certificatesresolvers.dev.acme.storage=/letsencrypt/acme.json
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt

  mcp:
    build:
      context: ./sample-deep-research-mcp
    env_file: .env
    environment:
      BIND_HOST: 0.0.0.0
      BIND_PORT: 8000
      TRANSPORT: sse
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mcp.rule=Host(`mcp.localhost`)
      - traefik.http.routers.mcp.entrypoints=websecure
      - traefik.http.routers.mcp.tls=true
      - traefik.http.routers.mcp.tls.certresolver=dev
      - traefik.http.services.mcp.loadbalancer.server.port=8000

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: ["start"]
    environment:
      KC_PROXY: edge
      KC_HOSTNAME: auth.localhost
      KC_HTTP_ENABLED: "true"
    expose:
      - "8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kc.rule=Host(`auth.localhost`)
      - traefik.http.routers.kc.entrypoints=websecure
      - traefik.http.routers.kc.tls=true
      - traefik.http.routers.kc.tls.certresolver=dev
      - traefik.http.services.kc.loadbalancer.server.port=8080
      # Optional RFC 8414 path-insert shim
      - traefik.http.routers.kc-discovery.rule=Host(`auth.localhost`) && PathPrefix(`/.well-known/`)
      - traefik.http.routers.kc-discovery.entrypoints=websecure
      - traefik.http.routers.kc-discovery.tls=true
      - traefik.http.routers.kc-discovery.middlewares=kc-discovery-rewrite
      - traefik.http.routers.kc-discovery.priority=100
      - traefik.http.routers.kc-discovery.service=kc
      - traefik.http.middlewares.kc-discovery-rewrite.replacepathregex.regex=^/\.well-known/(.*)
      - traefik.http.middlewares.kc-discovery-rewrite.replacepathregex.replacement=/realms/mcp/.well-known/$${1}

volumes:
  traefik_data: {}
