[tool.ruff]
target-version = "py311"
src = [
  "fastmcp/src",
  "tests",
  "sample-deep-research-mcp",
  "scripts",
]

[tool.ruff.lint]
extend-select = ["I", "UP"]

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"

